projects:

  cluster-config:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: cluster-gitops
      notifications.argoproj.io/subscribe.on-health-degraded.slack: cluster-gitops
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
    - ${INFRA_GITOPS_REPO}
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications: 

# Basic

  web-terminal-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/web-terminal-operator 

# Storage

  trident-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'      
    source:
      path: components/trident-operator

  trident-instance:
    annotations:
      argocd.argoproj.io/sync-wave: '6'      
    source:
      path: components/trident-instance

  minio-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5' 
    destination:
      namespace: minio-operator           
    source:
      path: components/minio-operator

# Observability

  kube-ops-view:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: kube-ops-view
    source:
      path: components/kube-ops-view 

  loki-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'            
    source:
      path: components/loki-operator

  loki-logging-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15' 
    destination:
      namespace: openshift-logging           
    source:
      path: components/loki-logging-configuration

  openshift-logging-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'           
    source:
      path: components/openshift-logging-operator              

  openshift-logging-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15' 
    destination:
      namespace: openshift-logging           
    source:
      path: components/openshift-logging-configuration    

  cluster-observability-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'            
    source:
      path: components/cluster-observability-operator  

  kubecost-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'            
    source:
      path: components/kubecost-operator

  kubecost-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15'            
    source:
      path: components/kubecost-configuration                  

# Networking

  cert-manager-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/cert-manager-operator

  cert-manager-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: cert-manager
    source:
      path: components/cert-manager-configuration

  external-dns-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/external-dns-operator

  external-dns-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: external-dns
    source:
      path: components/external-dns-configuration      

  metallb-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/metallb-operator

  nmstate-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/nmstate-operator 

  nmstate-instance:
    annotations:
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: openshift-nmstate
    source:
      path: components/nmstate-instance

              