default: {}     

projects:

  cluster-config:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: cluster-gitops
      notifications.argoproj.io/subscribe.on-health-degraded.slack: cluster-gitops
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
    #- ${INFRA_GITOPS_REPO}
    - https://github.com/mnoble1971/virtualization-migration-factory-reference-implementation.git
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications: 

# Basic

  web-terminal-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-operators
    source:
      path: components/web-terminal-operator 



# Observability

  kube-ops-view:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: kube-ops-view
    source:
      path: components/kube-ops-view 

# Network 
  nmstate-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-nmstate
    source:
      path: components/nmstate-operator 

  nmstate-instance:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: openshift-nmstate
    source:
      path: components/nmstate-instance

  nmstate-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '7'
    destination:
      namespace: openshift-nmstate
    source:
      path: components/nmstate-configuration            

# # LVM configuration
#   lvm-configuration:
#     annotations:
#       argocd.argoproj.io/compare-options: IgnoreExtraneous
#       argocd.argoproj.io/sync-wave: '4'
#     destination:
#       namespace: openshift-storage
#     source:
#       path: components/lvm-configuration   

# external secrets manager
  external-secrets-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: external-secrets-operator
    source:
      path: components/external-secrets-operator           

# vault config operator
  # vault-config-operator:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '6'
  #   destination:
  #     namespace: vault-config-operator
  #   source:
  #     path: components/vault-config-operator        


# htpasswd creation
  htpasswd-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '1'
    destination:
      namespace: default
    source:
      path: components/htpasswd-configuration         
           
# # Lightspeed
 
#   lightspeed-operator:
#     annotations:
#       argocd.argoproj.io/compare-options: IgnoreExtraneous
#       argocd.argoproj.io/sync-wave: '5'
#     destination:
#       namespace: openshift-lightspeed
#     source:
#       path: components/lightspeed-operator 

#   lightspeed-configuration:
#     annotations:
#       argocd.argoproj.io/compare-options: IgnoreExtraneous
#       argocd.argoproj.io/sync-wave: '7'
#     destination:
#       namespace: openshift-lightspeed
#     source:
#     path: components/lightspeed-configuration