apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-collector

resources:
  - ./namespace.yaml
  #- ./collector.yaml
  - ./rbac.yaml
  - ./service-account.yaml
  - ./cluster-metrics-collector.yaml