apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespaces.yaml
- ./istio.yaml
- ./udns.yaml
- ./istiocni.yaml
#- ./gateway.yaml
#- ./virtual-service.yaml
- ./certificate.yaml
- ./vms.yaml
- ./gateway-api-gateway.yaml


# helmGlobals:
#   chartHome: ../../../../.helm-charts

# helmCharts:
#   - name: gateway
#     releaseName: vm-yellow-ingressgateway
#     namespace: vm-yellow
#     valuesFile: ingress-gateway-values.yaml